name: covid_growth
channels:
  - conda-forge
  - defaults
  - ak_93
  - ecrop
dependencies:
  - appnope=0.1.0=py37hc8dfbb8_1001
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.4=pyh9f0ad1d_0
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37hc8dfbb8_1
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1001
  - freetype=2.10.1=h8da9a1a_0
  - importlib-metadata=1.5.2=py37hc8dfbb8_0
  - importlib_metadata=1.5.2=0
  - ipykernel=5.2.0=py37h43977f1_1
  - ipython=7.13.0=py37hc8dfbb8_2
  - ipython_genutils=0.2.0=py_1
  - jedi=0.16.0=py37hc8dfbb8_1
  - jinja2=2.11.1=py_0
  - jsonschema=3.2.0=py37hc8dfbb8_1
  - jupyter_client=6.1.2=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_1
  - kiwisolver=1.1.0=py37ha1cc60f_1
  - libblas=3.8.0=16_openblas
  - libcblas=3.8.0=16_openblas
  - libcxx=9.0.1=1
  - libffi=3.2.1=h4a8c4bd_1007
  - libgfortran=4.0.0=2
  - liblapack=3.8.0=16_openblas
  - libopenblas=0.3.9=h3d69b6c_0
  - libpng=1.6.37=hbbe82c9_1
  - libsodium=1.0.17=h01d97ff_0
  - llvm-openmp=9.0.1=h28b9765_2
  - markupsafe=1.1.1=py37h9bfed18_1
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py37hddda452_0
  - mistune=0.8.4=py37h0b31af3_1000
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.4=py_0
  - ncurses=6.1=h0a44026_1002
  - notebook=6.0.3=py37_0
  - numpy=1.18.1=py37h7687784_1
  - openssl=1.1.1e=h0b31af3_0
  - pandas=1.0.3=py37h94625e5_0
  - pandoc=2.9.2=0
  - pandocfilters=1.4.2=py_1
  - parso=0.6.2=py_0
  - pexpect=4.8.0=py37hc8dfbb8_1
  - pickleshare=0.7.5=py37hc8dfbb8_1001
  - pip=20.0.2=py_2
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - ptyprocess=0.6.0=py_1001
  - pygments=2.6.1=py_0
  - pyparsing=2.4.6=py_0
  - pyrsistent=0.16.0=py37h9bfed18_0
  - python=3.7.6=h90870a6_5_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - pyzmq=19.0.0=py37haec44b1_1
  - readline=8.0=hcfe32e1_0
  - scipy=1.4.1=py37h82752d6_0
  - send2trash=1.5.0=py_0
  - setuptools=46.1.3=py37hc8dfbb8_0
  - six=1.14.0=py_1
  - sqlite=3.30.1=h93121df_0
  - terminado=0.8.3=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbbe82c9_0
  - tornado=6.0.4=py37h9bfed18_1
  - traitlets=4.3.3=py37hc8dfbb8_1
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - xz=5.2.4=h0b31af3_1002
  - zeromq=4.3.2=h6de7cb9_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h0b31af3_1006
prefix: /Users/voegtlil/miniconda3/envs/covid_growth

